'use client';

import React, { useState } from 'react';
import { HelpCircle, ChevronDown, ChevronUp } from 'lucide-react';

export const FaqSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      q: 'How does CivicLens AI determine which government schemes I am eligible for?',
      a: 'CivicLens AI uses a combination of structured policy rules and Gemini Generative AI matching algorithms. When you enter your age, state, occupation, annual income, and category, the system evaluates parameters against 40+ Central & State scheme guidelines (e.g. PM-KISAN, Startup India, Ayushman Bharat, Post-Matric Scholarships) to produce accurate match scores and eligibility reasons.'
    },
    {
      q: 'Can CivicLens AI help me understand official Government Gazette Notifications & GR documents?',
      a: 'Yes! Using the "Doc Explainer" feature, you can paste text or upload government notices, resolution PDFs, or application forms. Gemini AI summarizes complex administrative language into plain terms, extracts mandatory deadlines, translates difficult legal jargon into simple definitions, and outlines required action steps.'
    },
    {
      q: 'Which Indian languages are supported for voice and text interaction?',
      a: 'CivicLens AI currently supports 8 major Indian languages: English, Hindi (हिंदी), Telugu (తెలుగు), Tamil (தமிழ்), Kannada (ಕನ್ನಡ), Malayalam (മലയാളം), Bengali (বাংলা), and Marathi (मराठी). You can toggle the UI language instantly or use the Speech-to-Text microphone button to speak naturally in your native language.'
    },
    {
      q: 'Is my personal data kept safe and private?',
      a: 'Absolutely. CivicLens AI follows strict data privacy standards aligned with Google Cloud Security and SAIF principles. No personal identity data or document uploads are sold or shared with third parties, and all local API credentials are encrypted.'
    },
    {
      q: 'Where do I get official application forms and links to submit my scheme application?',
      a: 'Every scheme card and AI answer generated by CivicLens AI includes direct links to official government portals (such as pmkisan.gov.in, seedfund.startupindia.gov.in, passportindia.gov.in, etc.) alongside a step-by-step action plan guiding you from registration to final disbursement.'
    }
  ];

  return (
    <section className="py-16 bg-slate-50/50 dark:bg-slate-900/50 border-t border-slate-200/60 dark:border-slate-800">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="text-center mb-12 space-y-3">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300 text-xs font-semibold">
            <HelpCircle className="w-3.5 h-3.5" />
            <span>Frequently Asked Questions</span>
          </div>
          <h2 className="text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">
            Got Questions? We Have Answers.
          </h2>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={idx}
                className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-sm transition-all"
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : idx)}
                  className="w-full px-6 py-4 text-left font-bold text-sm text-slate-900 dark:text-white flex items-center justify-between gap-4 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
                >
                  <span>{faq.q}</span>
                  {isOpen ? (
                    <ChevronUp className="w-4 h-4 text-blue-500 shrink-0" />
                  ) : (
                    <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" />
                  )}
                </button>

                {isOpen && (
                  <div className="px-6 pb-5 text-xs text-slate-600 dark:text-slate-300 leading-relaxed border-t border-slate-100 dark:border-slate-800/60 pt-3">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};
